spring:
  application:
    name: EmployeeManagement
  datasource:
    url: jdbc:sqlserver://10.2.1.4:52752;databaseName=mule_training_db;encrypt=true;trustServerCertificate=true;
    username: poc_dev_user
    password: FeA2da1pfWBbPXVDK87z0t
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
